# Generated by Django 4.0.6 on 2022-07-27 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapi.blog_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapi.blog_management.models.upload_path)),
                ('catagory', models.CharField(choices=[('1', 'Mental Health'), ('2', 'Heart Disease'), ('3', 'Covid19'), ('4', 'Immunization')], max_length=20)),
                ('summary', models.CharField(max_length=15)),
                ('content', models.TextField(max_length=100)),
                ('is_draft', models.BooleanField(blank=True, default=False, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
